[[redirects]]
  from = "/todolist"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/movies"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/movie"
  to = "index.html"
  status = 302
  query = {id = ":id"}
[[redirects]]
  from = "/fakestore"
  to = "index.html"
  status = 200
 

      
