[[redirects]]
  from = "/todolist"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/movies"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/movie/:id"
  to = "index.html"
  status = 200
[[redirects]]
  from = "/movies"
  to = "/movie/:id"
  status = 301  

      
